// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe5iZ-gplP-NawteR5BwQ2flLjoBYoDsU',
    appId: '1:814524140629:web:95c88b31803fcca9a018dc',
    messagingSenderId: '814524140629',
    projectId: 'to-do-app-21119',
    authDomain: 'to-do-app-21119.firebaseapp.com',
    databaseURL: 'https://to-do-app-21119-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-app-21119.appspot.com',
    measurementId: 'G-KLDN91VLVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVa_fdiWf-1mAE7Zt3JaXZzkJH4tKKArw',
    appId: '1:814524140629:android:de0825b2ef1cfe48a018dc',
    messagingSenderId: '814524140629',
    projectId: 'to-do-app-21119',
    databaseURL: 'https://to-do-app-21119-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-app-21119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO5pCACHbXC6_NEChunNGYoLe57jCn-Q4',
    appId: '1:814524140629:ios:e796bf0e2032c3eca018dc',
    messagingSenderId: '814524140629',
    projectId: 'to-do-app-21119',
    databaseURL: 'https://to-do-app-21119-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-app-21119.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO5pCACHbXC6_NEChunNGYoLe57jCn-Q4',
    appId: '1:814524140629:ios:dd22c178cefa49bba018dc',
    messagingSenderId: '814524140629',
    projectId: 'to-do-app-21119',
    databaseURL: 'https://to-do-app-21119-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-app-21119.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
